# Generated by Django 5.1.3 on 2024-11-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loyalty_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
