# Generated by Django 5.1.3 on 2024-12-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_user_loyalty_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_number',
            field=models.PositiveIntegerField(default=22),
        ),
    ]
